### ISSUE TITLE
Large FIle Size greater than 50 MB are cant upload in autodesk Forge

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#105]
I am trying to upload file Greater than 50 MB but it wont get upload i found out the Code resumableUploadFile in that unable to find out the FIle path and the Session Id Regarding the RandomString help me to resolve the issue

**Comment by cyrillef** [comment]
You should be using the new Direct S3 approach anyway.
I would recommend you use the uploadResources() method instead. It hides all the complexity of uploading large files using the S3 approach. See this example 
https://github.com/Autodesk-Forge/forge-api-dotnet-client/blob/master/DirectS3Advanced/Program.cs#L262
