### ISSUE TITLE
How to Get all Model Properties from Model Viewer by using API in that How to Pass Parameters  in Javascript and c# dot net Core Please Guide us to resolve the Issue 

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#106]
The Forge API we have in that what we need to Pass in URN and suppose we have rvt File the How to Extreact all Model Browser Properties in dot net core and Javascript

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to this SDK. Please send the questions on Forge services to
forge.help@autodesk.com
