### ISSUE TITLE
while fetching the manifest data on auto desk forge through API in postman got error "diagnostic": "The requested manifest urn is invalid." i am entering correct URN and api i am using is GET	https://developer.api.autodesk.com/modelderivative/v2/designdata/{urn}/manifest in that access token is also pass in correct manner in header can you please help me to resolve issue 

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#107]
API: GET	https://developer.api.autodesk.com/modelderivative/v2/designdata/{urn}/manifest 
Error:   "diagnostic": "The requested manifest urn is invalid." (400 Bad request)

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to this SDK. Please send Forge questions to
forge.help@autodesk.com
