### ISSUE TITLE
i am fetching metadata by using urn i call method from javascript jquery ajax call after calling the serverside method i got exception  'Autodesk.Forge.Model.Dynamic Json Response' does not contain a definition for 'GetAwaiter' i am using dot net core

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#108]
the client side code is 
function ObjectTree(node) {
    $("#forgeViewer").empty();
    if (node == null) node = $('#appBuckets').jstree(true).get_selected(true)[0];
    var bucketKey = node.parents[0];
    var objectKey = node.id;
    var urn = encodeURI(node.id);
    debugger;
    jQuery.get({
        url: '/api/forge/modelderivative/Metadata',
        contentType: 'application/json',
        data: { urn: urn},
        success: function (res) {
            console.log(res);
        },
    });
} 
and server side code is  
[HttpGet]
        [Route("api/forge/modelderivative/Metadata")]
        public async Task<dynamic> GetMetadata(string urn)
        {
            try
            {
                var acceptEncoding = "";
                dynamic oauth = await OAuthController.GetInternalAsync();
                DerivativesApi derivative = new DerivativesApi();
                derivative.Configuration.AccessToken =  oauth.access_token;
                dynamic response = await derivative.GetMetadata(urn, acceptEncoding);
                return response;
            }
            catch (Exception ex)
            {

                return (null);
            }
        }
the exception i got is Autodesk.Forge.Model.DynamicJsonResponse' does not contain a definition for 'GetAwaiter 
please help me to resolve the issue

**Comment by szilvaa-adsk** [comment]
Hi @Ashishoncode, what makes you believe that this has anything to do with the code in this repo? I don't see anything related to this repo when I look at the server code above.

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to this SDK. Please send Forge questions to
[forge.help@autodesk.com](mailto:forge.help@autodesk.com)
