### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established in postman 

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#111]
I Deployed  forge dot net core application on IIS and i am fetching the api from the postman by entering authentication token (bearer token) and the server IP as hostname followed by the route in dot net core application so while fetching data from the postman i got the error in the console of postman

error: Client network socket disconnected before secure TLS connection was established in postman

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to this SDK. Please send Forge questions to
[forge.help@autodesk.com](mailto:forge.help@autodesk.com)
