### ISSUE TITLE
The SSL connection could not be established in forge and dotnet core application 

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#112]
i have forge application with dot net core 5.0 we are hosted the application on the server so while fetching the api we got the error like  The SSL connection could not be established can you please help me to resolve the issue(Autodesk.forge.client.apiexception: error calling the get buckets :The SSL connection could not be established)

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to this SDK. Please send Forge questions to
[forge.help@autodesk.com](mailto:forge.help@autodesk.com)
