### ISSUE TITLE
Error While Translate File in the Bucket in autodesk forge

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#113]
We have Dotnet Core Application for front end we are using Angular in that Javascript plug in we are using to develop the UI part in that While Translating the File we got the error when we hit the jquery ajax call in that   url: 'https://developer.api.autodesk.com/modelderivative/v2/designdata/' + urn + '/manifest', while hitting the request we got error 401 unauthorized error can you please resolve the Issue locally its working fine when we are deploying on server its getting Issue

**Comment by Ashishoncode** [comment]
jQuery.ajax({
                    url: 'https://developer.api.autodesk.com/modelderivative/v2/designdata/' + urn + '/manifest',
                    headers: { 'Authorization': 'Bearer ' + access_token },

                    success: function (res) {

                        if (res.progress === 'success' || res.progress === 'complete') launchViewer(urn);
                        else $("#forgeViewer").html('The translation job still running: ' + res.progress + '. Please try again in a moment.');
                        console.log("urn working");

                    },
                    error: function (err) {
                        var msgButton = 'This file is not translated yet! ' +
                            '<button class="btn btn-xs btn-info" onclick="translateObject()"><span class="glyphicon glyphicon-eye-open"></span> ' +
                            'Start translation</button>'
                        $("#forgeViewer").html(msgButton);
                    }
                });

**Comment by Ashishoncode** [comment]
above jquery call url: 'https://developer.api.autodesk.com/modelderivative/v2/designdata/' + urn + '/manifest', it gives 401 error

**Comment by Ashishoncode** [comment]
Urn is already in encoded format and Postman also its Working Fine but on the UI side we got error please help us to resolve the issue

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to this SDK. Please send Forge questions to
[forge.help@autodesk.com](mailto:forge.help@autodesk.com)
