### ISSUE TITLE
Colouring of Elements in Revit File

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#115]
HI , I am Creating application with c# and javascript in the revit File i need to colour element in the revit file by fetching Properties of element , the Coloring is done by only Vector4 but if i want to use the Colour pallete and select the Colour and colour the element i am unable to colour that by using colour pallete can you please help me to resolve the issue

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to this SDK. Please ask questions on Revit API at [Revit API Forum](https://forums.autodesk.com/t5/revit-api-forum/bd-p/160)
