### ISSUE TITLE
AutoDesk Forge Viewer Getting Zoom in and Out Frequently

### ISSUE THREAD

**Issue by Ashishoncode** [Autodesk-Forge/forge-api-dotnet-core#127]
HI Team, Currently we are Implementing one scenario in that Revit Element are getting Visible and Color through the Proper Sequence but while Implementing this Autodesk Forge Viewer Is getting Zoom in and Out Frequently Can You Please guide us to resolve the Issue 

Issues
1. How To Prevent the Zoom in and out while Visible and Color the Revit Element

**Comment by zhuliice** [comment]
@Ashishoncode We only take care of questions/issues related to Design Automation SDK. Please send the questions to
[forge.help@autodesk.com](mailto:forge.help@autodesk.com)
