### ISSUE TITLE
HttpRequestException.StatusCode is not set

### ISSUE THREAD

**Issue by provegard** [Autodesk-Forge/forge-api-dotnet-core#70]
The `EnsureSuccessStatusCodeAsync` method doesn't set `HttpRequestException.StatusCode`:

https://github.com/Autodesk-Forge/forge-api-dotnet-core/blob/main/src/Autodesk.Forge.Core/HttpResponseMessageExtensions.cs#L41

The current workaround is to check if the message contains "status code N".

**Comment by zhuliice** [comment]
@provegard thanks for reporting. We will migrate this project to .Net 5 first and fix this issue

**Comment by provegard** [comment]
Sounds good! I assume Autodesk.Forge and Autodesk.Forge.DesignAutomation will be migrated to .NET 5 as well? I use them both from a .NET 5 project, and while there are a lot of build/restore warnings, they work just fine.

**Comment by provegard** [comment]
By the way, if the error is 429 (too many requests), I'd like to read the Retry-After header, so it would be useful to have headers in the exception (or at least the Retry-After time).

**Comment by zhuliice** [comment]
> Sounds good! I assume Autodesk.Forge and Autodesk.Forge.DesignAutomation will be migrated to .NET 5 as well? 

That is right. 

>  if the error is 429 (too many requests), I'd like to read the Retry-After header, so it would be useful to have headers in the exception (or at least the Retry-After time)

We will see what we can do for it

**Comment by zhuliice** [comment]
@provegard, the requests have been done by https://github.com/Autodesk-Forge/forge-api-dotnet-core/pull/71 and https://github.com/Autodesk-Forge/forge-api-dotnet-core/pull/72. 
The changes are released with version of `2.0.1` ([Autodesk.Forge.Core](https://www.nuget.org/packages/Autodesk.Forge.Core/))

**Comment by zhuliice** [comment]
I am closing this issue. Please let us know if you have any question.
